name: Lint App1 Code Base

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    paths:
      - 'app1/**.py'

jobs:
  run-app1-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8==5.0.4
        pip install black==23.3.0

    - name: Get changed files
      uses: tj-actions/changed-files@v35
      id: changed-files
      with:
        files: app1/**

    - name: Analyzing the code with flake8
      run: |
        files=""
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if [[ $file == *.py ]]; then
            files="$files $file"
          fi
        done
        if [ -n "$files" ]; then
          flake8 $files --config app1/.flake8
        fi
